---
deployer:
  chef:
    roles:
      - clc:
        - eucalyptus::cloud-controller
        - eucalyptus::register-components
      - user-facing:
        - eucalyptus::user-facing
        - eucalyptus::user-console
      - walrus:
        - eucalyptus::walrus
      - cluster-controller:
        - eucalyptus::cluster-controller
      - storage-controller:
        - eucalyptus::storage-controller
      - node-controller:
        - eucalyptus::node-controller
      - midolman:
        - midokura::midolman
      - midonet-gw:
        - midokura
      - mon-bootstrap:
        - ceph-cluster::mon-bootstrap
      - ceph-mons:
        - ceph-cluster::mons
      - ceph-osds:
        - ceph-cluster::osds
      - riak-head:
        - riakcs-cluster::ttyfix
        - riak-cs::package
        - riak
        - sysctl
        - riak-cs
        - riak-cs::stanchion
        - riak-cs::control
        - riak-cs-create-admin-user
        - riakcs-cluster::credentials
        - riakcs-cluster::sync
      - riak-node:
        - riakcs-cluster::ttyfix
        - riakcs-cluster::sync
        - riak-cs::package
        - riak
        - sysctl
        - riak-cs
        - riakcs-cluster::join
        - riakcs-cluster::mergecreds
